// 1. Create 3 different lists data types that will include things found in grocery store. Make sure your items use the string data type.
// Create a list that includes 5 items that you can find in the frozen food isle.
// Create a list that includes 5 items that you can find in the international food isle.

1. "FROZEN FOOD ISLE :"
frozen_foods= [ " Frozen pizza" , "Ice cream", " Frozen vegetables", " Frozen chickn nuggets", "Frozen waffles"]

2. "INTERNATIONAL FOOD ISLE"
International_foods = ["Sushi rice" , " Taco Shells" , "Curry paste" , "Soy Sauce" , "Sriracha sauce"]

3. "PRODUCE ISLE"
Fresh_Produce = ["Banana" , "Spinach" , " Tomato ", "Carrots" , "Avocados"]

Create a list that includes 5 items that you can find in the produce isle.
2. With the list provided below; use the print (for python) or console.log (for javascript) functions to return the correct value for the index.
numbers = [1,30,39,50,293,100]

Hint: If you get stuck, search for accessing JS list by index or accessing Python list by index depending on which language you are learning.

PYTHON:
numbers = [1 , 30 , 39 , 50 , 293 , 100]
Print(numbers[0]); # First Item : 1
Print(number[2]);  # Third Item: 39
Print(number[4]);  # Fifth Item: 293



print/ console.log the number at index 0
print/ console.log the number at index 3
print/ console.log the number at index 4
3. Create a function that will multiply the number at index 4 in the list above.

Print(numbers[0])
Print(numbers[3])
Print(numbers[4])