1. Create 3 different lists data types that will include things found in grocery store. Make sure your items use the string data type.
Create a list that includes 5 items that you can find in the frozen food aisle. ['frozen waffles','hot pockets','frozen pizzas','frozen broccoli','frozen vegetables']
Create a list that includes 5 items that you can find in the international food aisle. ['goya green peas','german sausages','coffee','pancakes','sushi']
Create a list that includes 5 items that you can find in the produce aisle. ['red apples','red raspberries','blueberries','blackberries','meyer lemons']

2. With the list provided below; use the print (for python) or console.log (for javascript) functions to return the correct value for the index.
numbers = [1,30,39,50,293,100]

Hint: If you get stuck, search for accessing JS list by index or accessing Python list by index depending on which language you are learning

print/ console.log the number at index 1
print/ console.log the number at index 30
print/ console.log the number at index 39
print/ console.log the number at index 50
print/ console.log the number at index 100
print/ console.log the number at index 293

3. Create a function that will multiply the number at index 4 in the list above.